### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mysterymath** [sgadrat/6502-compilers-bench#1]
Hi,

I'm one of the LLVM-MOS codegen authors, and I'm looking to incorporate this benchmark into our integration test suite. However, there's no license on this repo that would allow me to do so. Would you mind licensing this under a free or open source license?

Thanks,
Daniel

**Comment by sgadrat** [comment]
Hello,

Added 2-clause BSD license to both "master" and "llvm-mos" branches. I hope it suits your needs, if not tell me. I did not expect this code to live longer than the writing of bench blog-post.

Commits:
* master: 51b3d645adf67397cc3ed11ee02b0db6aadecef4
* llvm-mos: 617c804fe504ebed17a5fd6749bc5860371c8f32

Happy to see llvm-mos being worked on,
Sylvain

**Comment by mysterymath** [comment]
Hah, there's no telling what can come of a simple blog post! Thanks!
